# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'incompressibleRASModels'

sources = Split("""
RASModel/RASModel.cpp
laminar/RASLaminar.cpp
realizableKE/realizableKE.cpp
kEpsilon/kEpsilon.cpp
SpalartAllmaras/SpalartAllmaras.cpp
kOmegaSST/kOmegaSST.cpp
kOmegaSSTSAS/kOmegaSSTSAS.cpp
gammaReTheta/gammaReTheta.cpp
""")

caelus_inc = [
'transportModels',
'turbulenceModels'
]

caelus_libs = [
'core',
'incompressibleTurbulenceModel'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
