# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'specie'

sources = Split("""
atomicWeights/atomicWeights.cpp
specie/specie.cpp
reaction/specieCoeffs/specieCoeffs.cpp
reaction/reactions/makeReactions.cpp
reaction/reactions/makeLangmuirHinshelwoodReactions.cpp
reaction/reactions/makeMichaelisMentenReactions.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
