# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'twoPhaseInterfaceProperties'

sources = Split("""
alphaContactAngle/alphaContactAngle/alphaContactAngleFvPatchScalarField.cpp
alphaContactAngle/constantAlphaContactAngle/constantAlphaContactAngleFvPatchScalarField.cpp
alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.cpp
alphaContactAngle/timeVaryingAlphaContactAngle/timeVaryingAlphaContactAngleFvPatchScalarField.cpp
alphaFixedPressure/alphaFixedPressureFvPatchScalarField.cpp
""")

caelus_inc = [
'transportModels/interfaceProperties/lnInclude'
]

caelus_libs = [
'core'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
