# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'forces'

sources = Split("""
forces/forces.cpp
forces/forcesFunctionObject.cpp
forceCoeffs/forceCoeffs.cpp
forceCoeffs/forceCoeffsFunctionObject.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'thermophysicalModels/basic/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'transportModels',
'turbulenceModels'
]

caelus_libs = [
'core',
'specie',
'incompressibleTransportModels',
'incompressibleRASModels',
'incompressibleLESModels',
'incompressibleVLESModels',
'fluidThermophysicalModels',
'compressibleRASModels',
'compressibleLESModels',
'compressibleVLESModels',
'incompressibleTurbulenceModel',
'compressibleTurbulenceModel'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
