# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'conversion'

sources = Split("""
ensight/file/ensightFile.cpp
ensight/file/ensightGeoFile.cpp
ensight/part/ensightPart.cpp
ensight/part/ensightPartIO.cpp
ensight/part/ensightPartCells.cpp
ensight/part/ensightPartFaces.cpp
ensight/part/ensightParts.cpp
meshTables/boundaryRegion.cpp
meshTables/cellTable.cpp
meshReader/meshReader.cpp
meshReader/meshReaderAux.cpp
meshReader/calcPointCells.cpp
meshReader/createPolyCells.cpp
meshReader/createPolyBoundary.cpp
meshReader/starcd/STARCDMeshReader.cpp
meshWriter/meshWriter.cpp
meshWriter/starcd/STARCDMeshWriter.cpp
polyDualMesh/polyDualMesh.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
