# -*- mode: python -*-

from build import build_app
Import('env')

target = "potentialSolver"

sources = Split("""
potentialSolver.cpp
""")

caelus_inc = [
'sampling/lnInclude'
]

caelus_libs = [
'core',
'sampling'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
