# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'interfaceProperties'

sources = Split("""
interfaceProperties.cpp
interfaceCompression/interfaceCompression.cpp
dynamicCompression/dynCompressionModel.cpp
dynamicCompression/newDynCompressionModel.cpp
dynamicCompression/static/staticCompression.cpp
""")

caelus_inc = [
'finiteVolume/lnInclude',
'transportModels/twoPhaseInterfaceProperties/alphaContactAngle/alphaContactAngle'
]

caelus_libs = [
'core',
'twoPhaseInterfaceProperties'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
