# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'pairPatchAgglomeration'

sources = Split("""
pairPatchAgglomeration.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
