# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'IOFunctionObjects'

sources = Split("""
partialWrite/partialWrite.cpp
partialWrite/partialWriteFunctionObject.cpp
removeRegisteredObject/removeRegisteredObject.cpp
removeRegisteredObject/removeRegisteredObjectFunctionObject.cpp
writeDictionary/writeDictionary.cpp
writeDictionary/writeDictionaryFunctionObject.cpp
writeRegisteredObject/writeRegisteredObject.cpp
writeRegisteredObject/writeRegisteredObjectFunctionObject.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
