# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'combustionModels'

sources = Split("""
combustionModel/combustionModel.cpp
CombustionModel_/CombustionModel/CombustionModels.cpp
diffusion/diffusions.cpp
infinitelyFastChemistry/infinitelyFastChemistrys.cpp
PaSR/PaSRs.cpp
EDC/EDCs.cpp
laminar/laminars.cpp
FSD/reactionRateFlameAreaModels/consumptionSpeed/consumptionSpeed.cpp
FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameArea.cpp
FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameAreaNew.cpp
FSD/reactionRateFlameAreaModels/relaxation/relaxation.cpp
FSD/FSDs.cpp
noCombustion/noCombustions.cpp
""")

caelus_inc = [
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/chemistryModel/lnInclude',
'turbulenceModels/compressible/turbulenceModel',
'turbulenceModels/compressible/LES/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'turbulenceModels/LES/LESfilters/lnInclude'
]

caelus_libs = [
'core',
'chemistryModel',
'compressibleLESModels',
'reactionThermophysicalModels',
'fluidThermophysicalModels'
]

prepend_args = { 'CXXFLAGS' : ['-DCONST_TMP'] }

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
